name: Android CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Android Github Action
      uses: Vukan-Markovic/Github-Android-Action@1.2
    - name: Send some mail
      uses: wadeww/send-email-action@master
      with:
       server_address: smtp.gmail.com
       port: 465
       username: mejdihafiane@gmail.com
       password: azma4everfuck14
       subject: Workflow finished
       body: Job completed ${{job.status}}
       to: mejdiblubiste@gmail.com
       from: Me

